// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw9D5VwRdcu4LSlg-OpnMc09ieTj1DkVs',
    appId: '1:882142075714:web:e9f7a6d64ea6e18e8b86db',
    messagingSenderId: '882142075714',
    projectId: 'lighthouse-app-dev',
    authDomain: 'lighthouse-app-dev.firebaseapp.com',
    storageBucket: 'lighthouse-app-dev.appspot.com',
    measurementId: 'G-VRQ6K94XQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZUlbnKsJihZ1S2NRB-LbwMVuk5r3M9ZM',
    appId: '1:882142075714:android:e1e4bdf2c829d7fe8b86db',
    messagingSenderId: '882142075714',
    projectId: 'lighthouse-app-dev',
    storageBucket: 'lighthouse-app-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmySyI9qsliieF5NstoVmGQzVvCOsRV-8',
    appId: '1:882142075714:ios:cc47e6619029bb7a8b86db',
    messagingSenderId: '882142075714',
    projectId: 'lighthouse-app-dev',
    storageBucket: 'lighthouse-app-dev.appspot.com',
    androidClientId: '882142075714-92baom2avf48kiq6rf8bb3u6for2dhod.apps.googleusercontent.com',
    iosClientId: '882142075714-h2docoegg2758tpv13ada1asdr3svd8k.apps.googleusercontent.com',
    iosBundleId: 'com.lighthouse',
  );
}
